language: node_js

node_js:
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'

os:
    - linux

install:
    - npm install

script:
    - if [ "$TRAVIS_NODE_VERSION" == "14" ]; then npm run-script coverage; else npm test; fi

after_success:
    - if [ "$TRAVIS_NODE_VERSION" == "14" ]; then npm install https://github.com/alekitto/ocular.js.git; fi
    - if [ "$TRAVIS_NODE_VERSION" == "14" ]; then $(npm bin)/ocular coverage/clover.xml; fi

jobs:
    include:
        - stage: lint
          node_js: "14"
          os: linux
          script:
              - npm install -g eslint
              - npm run-script lint
